
bk72xx:
  board: generic-bk7231n-qfn32-tuya

binary_sensor:
  - platform: gpio
    id: button
    name: Button
    pin:
      number: P6
      inverted: true
      mode:
        input: true
        pullup: true

text_sensor:
  - platform: template
    name: "IR Receiver"
    id: ir_receiver_sensor
    lambda: 'return {""};'
    update_interval: 60s

remote_receiver:
  id: ir_receiver
  pin:
    number: P16
    inverted: true
    mode:
      input: true
      pulldown: true
  dump: pioneer
  on_pioneer: 
    then:
      - text_sensor.template.publish:
          id: ir_receiver_sensor
          state: !lambda '
            switch(x.rc_code_1){
              case 0x0045:
                return "On";
              case 0x0046:
                return "Timer";
              case 0x0047:
                return "Off";
              case 0x0044:
                return "Mode 1";
              case 0x0043:
                return "Mode 2";
              case 0x0007:
                return "Mode 3";
              case 0x0009:
                return "Mode 4";
              case 0x0016:
                return "Mode 5";
              case 0x000D:
                return "Mode 6";
              case 0x000C:
                return "Mode 7";
              case 0x005E:
                return "Mode 8";
              case 0x0008:
                return "Dim Down";
              case 0x005A:
                return "Dim Up";
              default:
                return "";
            }
            '
      - delay: 100ms
      - text_sensor.template.publish:
          id: ir_receiver_sensor
          state: !lambda 'return "";'

output:
  - platform: libretiny_pwm
    id: output_1
    pin: P7
  - platform: libretiny_pwm
    id: output_2
    pin: P8

light:
  - platform: hbridge
    id: fairy_light
    name: Light
    pin_a: output_1
    pin_b: output_2