
bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    options:
      LT_UART_DEFAULT_PORT: 1 # output ESPHome log messages on UART1 (upload UART)

external_components:
  # - source: 
  #     type: local
  #     path: components
  #   components: [lt_hbridge]
  - source: github://LeoDJ/tuya-ir-string-lights
    components: [lt_hbridge]

binary_sensor:
  - platform: gpio
    id: button
    name: Button
    pin:
      number: P6
      inverted: true
      mode:
        input: true
        pullup: true

text_sensor:
  - platform: template
    name: "IR Receiver"
    id: ir_receiver_sensor
    lambda: 'return {""};'
    update_interval: 60s

remote_receiver:
  id: ir_receiver
  pin:
    number: P16
    inverted: true
    mode:
      input: true
      pulldown: true
  dump: pioneer
  on_pioneer: 
    then:
      - text_sensor.template.publish:
          id: ir_receiver_sensor
          state: !lambda '
            switch(x.rc_code_1){
              case 0x0045:
                return "On";
              case 0x0046:
                return "Timer";
              case 0x0047:
                return "Off";
              case 0x0044:
                return "Mode 1";
              case 0x0043:
                return "Mode 2";
              case 0x0007:
                return "Mode 3";
              case 0x0009:
                return "Mode 4";
              case 0x0016:
                return "Mode 5";
              case 0x000D:
                return "Mode 6";
              case 0x000C:
                return "Mode 7";
              case 0x005E:
                return "Mode 8";
              case 0x0008:
                return "Dim Down";
              case 0x005A:
                return "Dim Up";
              default:
                return "";
            }
            '
      - delay: 100ms
      - text_sensor.template.publish:
          id: ir_receiver_sensor
          state: !lambda 'return "";'

light:
  - platform: lt_hbridge
    name: "Light"
    pin_a: P7     # outputs need to be on different PWM groups (P6/7: G0, P8/9: G1, P24/29: G2)
    pin_b: P8
    # default_transition_length: 0.5s
    # gamma_correct: 1.0
    # constant_brightness: true